//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogovor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dogovor()
        {
            this.StrSl = new HashSet<StrSl>();
        }
    
        public int Id { get; set; }
        public string IDKl { get; set; }
        public string IDAg { get; set; }
        public int IDTr { get; set; }
        public string Date { get; set; }
        public int IDGroup { get; set; }
        public string Described { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Tarif Tarif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StrSl> StrSl { get; set; }
        public virtual GroupDog GroupDog { get; set; }
    }
}
