//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StrSl
    {
        public int Id { get; set; }
        public string IDKl { get; set; }
        public string IDAg { get; set; }
        public int IDDogv { get; set; }
        public string Date { get; set; }
        public string Described { get; set; }
        public int IDGroup { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual Dogovor Dogovor { get; set; }
        public virtual GroupDog GroupDog { get; set; }
    }
}
